name: acil_durum_app
description: "Acil Durum Çağrı Uygulaması"
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  # Network & API
  http: ^1.4.0
  dio: ^5.4.0          # Added for better API handling and certificate management
  connectivity_plus: ^5.0.2  # Network connectivity tracking
  
  # Location services
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  
  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  cached_network_image: ^3.3.0  # For caching map tiles
  
  # UI components
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  shimmer: ^3.0.0      # Loading effects
  
  # Utils
  url_launcher: ^6.2.1
  intl: ^0.20.2        # For date/time formatting
  shared_preferences: ^2.2.2  # Local storage
  package_info_plus: ^4.2.0   # App version information
  device_info_plus: ^9.1.1    # Device information
  
  # State management (choose one based on preference)
  provider: ^6.1.1
  # OR
  # flutter_bloc: ^8.1.3
  # OR
  # get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # For generating app icons
  build_runner: ^2.4.6
  mockito: ^5.4.2      # For testing

# App icon configuration (uncomment and configure when icons are ready)
# flutter_icons:
#   android: "ic_launcher"
#   ios: true
#   image_path: "assets/icon/icon.png"
#   adaptive_icon_background: "#FF0000" # Red background
#   adaptive_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true
  
  # Uncomment and add your assets when ready
  # assets:
  #   - assets/images/
  #   - assets/icons/
  
  # Uncomment and add your fonts when ready
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700